name: Deploy Laravel Admin to Hpanel

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Admin Panel to Hpanel

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            # Path ke direktori admin di server
            ADMIN_DIR=/home/u982131153/domains/artiknesia.com/admin_ARTIKNESIA

            # Cek apakah direktori sudah ada, jika belum lakukan clone
            if [ ! -d "$ADMIN_DIR" ]; then
              git clone https://github.com/ahmakbardev/admin_ARTIKNESIA.git $ADMIN_DIR
            fi

            cd $ADMIN_DIR

            # Setup environment
            chmod +x ~/bin/composer
            echo "export PATH=$HOME/bin:$PATH" >> ~/.bash_profile
            echo "export PATH=$HOME/bin/node/bin:$PATH" >> ~/.bash_profile
            source ~/.bash_profile

            # Pull kode terbaru dari main
            git reset --hard
            git stash
            git pull origin main

            # Node.js setup
            which node
            node -v
            npm -v
            npm install --legacy-peer-deps
            npm run prod

            # Composer setup
            which composer
            $HOME/bin/composer --version
            $HOME/bin/composer install --no-dev --optimize-autoloader
            $HOME/bin/composer update --no-dev

            # Laravel setup
            php artisan key:generate
            php artisan migrate --force
            php artisan route:clear
            php artisan config:cache
            php artisan optimize

            # Setup symlink ke public_html jika belum ada
            if [ ! -L "/home/u982131153/domains/artiknesia.com/public_html/admin" ]; then
              ln -s $ADMIN_DIR/public/* /home/u982131153/domains/artiknesia.com/public_html/admin
            fi

            if [ ! -L "/home/u982131153/domains/artiknesia.com/public_html/storage" ]; then
              ln -s $ADMIN_DIR/public/storage/* /home/u982131153/domains/artiknesia.com/public_html/storage
            fi
